require "pp"
require "aws-sdk-core"
require "autostacker24"
require_relative "../lib/autocanary24/client"

task :default do

  Stacker.create_or_update_stack('autocanary24-example', 'base-stack.json', {})

  client = AutoCanary24::Client.new
  client.deploy_stack('autocanary24-example', 'asg-stack.json', {}, 'autocanary24-example')

end
