require "aws-sdk-core"
require "autostacker24"
require_relative "../lib/autocanary24/client"

STACK_NAME    = 'autocanary24-example'
BASE_TEMPLATE = 'base-stack.json'
ASG_TEMPLATE  = 'asg-stack.json'

task :default do

  # 1) Create the base stack which includes at least the ELB
  base_parameters = {}
  Stacker.create_or_update_stack(STACK_NAME, BASE_TEMPLATE, base_parameters)

  # 2) Create the stack which includes the ASG
  client = AutoCanary24::Client.new({
    :keep_inactive_stack => true
  })

  parameters = {}
  client.deploy_stack(STACK_NAME, ASG_TEMPLATE, parameters)

end

task :cleanup do
  Stacker.delete_stack('autocanary24-example-B')
  Stacker.delete_stack('autocanary24-example-G')
  Stacker.delete_stack('autocanary24-example')
end
